name: Pull Request Validation

on:
  pull_request:
    types: [opened, synchronize, labeled, unlabeled]
    branches:
      - main

jobs:
  static_analysis:
    name: Static analysis
    uses: ./.github/workflows/reusable-static-analysis.yaml

  label_pull_request:
    name: Label validation
    uses: ./.github/workflows/reusable-label-validation.yaml

  plan:
    name: Plan changes to prod
    needs:
      - static_analysis
      - label_pull_request
    uses: ./.github/workflows/reusable-terraform-workflow.yaml
    with:
      environment: non-prod
      apply: false
    secrets:
      ASSUME_ROLE: ${{ secrets.ASSUME_ROLE }}
